# Generated by Django 3.2.4 on 2021-06-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_job_jobposition_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='persons',
            field=models.ManyToManyField(through='core.Job', to='core.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='job_positions',
            field=models.ManyToManyField(through='core.Job', to='core.JobPosition'),
        ),
    ]
